language: node_js
node_js:
- '5'
script: make deploy
env:
  global:
  - GH_REF: github.com/asceresini/asceresini.github.io.git
  - secure: mk1F//sUM2nOn+//7KWOhmQH4RLOSA2e+EH88rlB3GlpVrP0VO4fHjaXw3LVtJoNd1/3PyZmoLguQcSwOUPsvW6STChQPKQ2zml39IfqZ9ck/PK4yzd130MztmUbjk1XTpBYEtA0sDy5+OYU+t6oIhSS2avSIOqVbVbY4YjK3NsplaeUPKyhwLs3nceWnfp68vWHAcxtFS2GFqVWErha+pX5p4JztwwSXFr+g+zs82+qi3s/zkCNHLHSWh7wv6NOHCHdLqhtoFUMEC/UfB9sbdt503d8IRE1//DGFFj/zTDHLBDQHE1ReBLUTTDqYCR+nzzrqVqLNjq6TzWGfk7CRiO0sSDXhClapFBK1oescmWRRe7Na2GrlOia2i423Kqu0e/90wBOLiLDcj08dMx+b50l2M7v4sP+nR10alfmH5w+BPXxBXBcfhcsQGaPNGsOfWwaDPfVEb4oO2U9ucwGdQ7hgb0pkjWK7R2BNxwLEgNy4NDseuYl0ikoablZg6Ys1LxEu0zSxuOuwGLUESFKd5bQAk28XJqbnI1EYMrq1DT6mdjgU2P3kRngGqVkA3AmJXS7SIVeOfwrgUa+shU460kkD5VQUdonGxobrvzxl04w5vkJzKxuLKnwFFsW/g7K/acmMDRrDCS7AO2zNiXXtM+yNx9pVtwJnrMoyMw1+lg=
