language: node_js
node_js:
- '5'
script: make deploy
env:
  global:
  - GH_REF: github.com/asceresini/asceresini.github.io.git
  - secure: Ri4Fy4zKPoiIx0l511mhWe1zLq9mezwDWkzrJ7vm3rgYQEomV8XyHwX5C3ZXhbj1VhbnOBh2UDppPjHwOdG7Yybz1NMKiUXwV4rjZ1WSKqFOMdO9+U6mMl42bOuDQnLyxsfd75PSX4HxcSk3LwPZot6UMFIWsy8EZ8n8k6s1NTkVMqSYCNlA4xkPMVGeu5aK/XSJW4U9NOaprMqGeLYp/SWw2IcyBfPua0OqFQTFrgxjABvs73D4tuHncntcqbTKbqg89Zy4UQ1NJZg8D6m9Q8RM7oeqcHtSPHmuaAsH66fPk2Sc+VY/yL+bwMGXtuEtBo6HlcaIP6CMlWkfr4zq+8Jf6yWAkVNCXNypyLnQV9iuqx0vq/BnXP/D0s77/fnG+Shg6uRayjxzRG+Rhm2cF2hu7rb6kesb+EqcSZx+ZH8wlOGD0W3s6dLl9XZWf+gHc9h8jVIMjTrb6/xpTY91V/f1fy1q2hvgwmQdqiu7mHjk731ElVyMfVYe8XP3A57t0cIH+azt27Xf0VPwDDhAS5mI24NTSByutuhTM7HWRNouc8q8TKaUerd4b34r6HQCEQrMQy7rbqf/yMuUsxi3In7lKj4nJDzsRzcmwV9zOGdrppKRcGs9MNaA3pW+OOvP/Xuw96p3Ej+HhPk2w+wMAsfx/NAcBuRb8WxvA6aY1Wo=
